import Link from "next/link";

const areas=[["01","ACCESS","Current financial information across authorised devices."],["02","COLLABORATE","Teams work from one connected accounting environment."],["03","INTEGRATE","Banking, sales, payroll and accounting systems can connect."],["04","SCALE","Infrastructure can grow without rebuilding the finance stack."]];

export default function CloudPage(){return <main className="topic-page"><header className="topic-nav"><Link href="/">THE LEDGER <span>/ 11</span></Link><div>05 / CLOUD + BIG DATA</div></header>
<section className="topic-hero"><span>05 · CLOUD + BIG DATA</span><div><h1>The ledger<br/><span>leaves</span><br/><em>the desk.</em></h1><p>Cloud accounting connects people, records and applications. Big data analytics adds a second layer: instead of only describing the past, finance teams can identify patterns, forecast scenarios and support decisions.</p></div><div className="hero-side-note">CONNECT → ANALYSE → PREDICT</div></section>
<section className="topic-section"><div className="section-label">CLOUD ACCOUNTING</div><div className="big-grid">{areas.map(([n,t,d])=><div key={n}><strong>{n}</strong><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="dashboard-large"><div className="section-label">A FINANCE CONTROL ROOM</div><div className="dash-metrics"><div><small>REVENUE</small><b>₹12.8M</b><em>+8.4%</em></div><div><small>NET MARGIN</small><b>18.6%</b><em>+2.1%</em></div><div><small>OPEN ITEMS</small><b>126</b><em>−14%</em></div><div><small>FORECAST</small><b>₹14.1M</b><em>NEXT QTR</em></div></div><div className="dash-bars">{[38,53,46,69,61,86,76,94].map((v,i)=><span key={i} style={{height:`${v}%`}} />)}</div><p className="dashboard-note">The value of analytics is not more charts. It is a better answer to the question: <em>what is changing?</em></p></section>
<section className="topic-callout"><span>DECISION VALUE</span><h2>Data only matters when it changes a <em>decision.</em></h2></section>
<section className="topic-section"><div className="section-label">THE TRADE-OFF</div><div className="topic-columns"><div><h2>More connection means more responsibility.</h2><p>Cloud and big-data systems increase the importance of cybersecurity, privacy, access rights, data quality, integration and compliance.</p></div><div><h3>Accountant as interpreter</h3><p>Technology can surface trends and forecasts. Professionals still decide what is material, reliable and relevant enough to act on.</p></div></div></section>
<footer className="topic-footer"><Link href="/blockchain">04 / ← BLOCKCHAIN</Link><Link href="/future">06 / FUTURE →</Link></footer></main>}
