import Link from "next/link";

const trends=[["01","AGENTIC AI","Systems moving beyond single prompts toward multi-step task execution."],["02","CONTINUOUS AUDIT","Connected data enables more continuous monitoring and exception review."],["03","EMBEDDED FINANCE","Financial capabilities increasingly sit inside wider digital workflows."],["04","INTELLIGENT FORECASTING","Models support scenarios, patterns and forward-looking decisions."]];

export default function FuturePage(){return <main className="topic-page"><header className="topic-nav"><Link href="/">THE LEDGER <span>/ 11</span></Link><div>06 / FUTURE ACCOUNTANT</div></header>
<section className="topic-hero"><span>06 · FUTURE</span><div><h1>Less<br/><span>recording.</span><br/><em>More meaning.</em></h1><p>The future accountant works with machines rather than competing with them. As structured work becomes automated, professional value shifts toward judgement, communication, governance and strategy.</p></div><div className="hero-side-note">PROCESS → JUDGEMENT → STRATEGY</div></section>
<section className="topic-section"><div className="section-label">WHAT IS EMERGING</div><div className="big-grid">{trends.map(([n,t,d])=><div key={n}><strong>{n}</strong><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="topic-section"><div className="section-label">THE NEW ACCOUNTANT</div><div className="skill-flow"><span>ACCOUNTING KNOWLEDGE</span><b>+</b><span>DATA LITERACY</span><b>+</b><span>TECH FLUENCY</span><b>+</b><span>PROFESSIONAL JUDGMENT</span></div><div className="topic-columns future-split"><div><h2>Know the numbers.</h2><p>But also understand the systems that create them, the assumptions behind them and the decisions they influence.</p></div><div><h3>Human advantage</h3><p>Context, scepticism, ethics, communication and judgement remain difficult to reduce to a button.</p></div></div></section>
<section className="topic-callout"><span>FINAL SHIFT</span><h2>Technology handles more of the <em>process.</em> Accountants create more of the <em>meaning.</em></h2></section>
<footer className="topic-footer"><Link href="/cloud">05 / ← CLOUD + DATA</Link><Link href="/case-files">07 / CASE STUDY →</Link></footer></main>}
