import Link from "next/link";

const blocks=[["01","TRANSACTION","An economic event is digitally recorded."],["02","BLOCK","Transactions are grouped and linked to prior records."],["03","SHARED HISTORY","Participants can verify the same agreed sequence."],["04","AUDIT TRAIL","The chain makes the path of a record easier to trace."]];

export default function BlockchainPage(){return <main className="topic-page"><header className="topic-nav"><Link href="/">THE LEDGER <span>/ 11</span></Link><div>04 / BLOCKCHAIN + SMART CONTRACTS</div></header>
<section className="topic-hero"><span>04 · BLOCKCHAIN</span><div><h1>One record.<br/><span>Many</span> proofs.<br/><em>Shared.</em></h1><p>Blockchain creates a linked record shared across participants. In accounting, its appeal is stronger traceability, shared verification and a clearer history of transactions.</p></div><div className="hero-side-note">RECORD → LINK → VERIFY</div></section>
<section className="topic-section"><div className="section-label">FROM EVENT TO CHAIN</div><div className="chain-large">{blocks.map(([n,t,d])=><div key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="topic-section"><div className="section-label">ACCOUNTING APPLICATIONS</div><div className="big-grid"><div><strong>01</strong><h3>Reconciliation</h3><p>A shared transaction history can reduce disagreement about which record is current.</p></div><div><strong>02</strong><h3>Verification</h3><p>Participants can use the same recorded history as evidence of the transaction trail.</p></div><div><strong>03</strong><h3>Smart contracts</h3><p>Pre-programmed rules can trigger defined actions when agreed conditions are met.</p></div><div><strong>04</strong><h3>Audit evidence</h3><p>Linked records can support traceability when the system is well designed and governed.</p></div></div></section>
<section className="topic-callout"><span>DO NOT CONFUSE RECORD WITH TRUTH</span><h2>A blockchain can preserve a record. It cannot automatically guarantee the <em>input was true.</em></h2></section>
<section className="topic-section"><div className="section-label">THE ACCOUNTING QUESTION</div><div className="topic-columns"><div><h2>Trust becomes a system design problem.</h2><p>Privacy, permissions, interoperability, scalability and governance all matter. The accounting benefit depends on who can write, who can verify and how the network is controlled.</p></div><div><h3>Triple-entry direction</h3><p>Blockchain research has explored how a shared third entry could complement conventional debit-and-credit records by making transaction evidence more difficult to alter silently.</p></div></div></section>
<footer className="topic-footer"><Link href="/rpa">03 / ← RPA</Link><Link href="/cloud">05 / CLOUD + BIG DATA →</Link></footer></main>}
