import Link from "next/link";

const facts=[["01","PARTNERS","Unisinos University + Dell Inc."],["02","TASK","Statutory reconciliation"],["03","INTERFACE","Chatbot + natural-language processing"],["04","METHOD","Technology Acceptance Model + user feedback"]];

export default function CaseFilesPage(){return <main className="topic-page"><header className="topic-nav"><Link href="/">THE LEDGER <span>/ 11</span></Link><div>07 / RESEARCH CASE</div></header>
<section className="topic-hero"><span>07 · CASE STUDY</span><div><h1>When AI<br/><span>meets</span><br/><em>accounting.</em></h1><p>A 2023 exploratory case study examined an ML-enabled accounting automation service developed with Dell Inc. The system used automation and a chatbot interface to support statutory reconciliation.</p></div><div className="hero-side-note">ML + AUTOMATION + ACCOUNTING</div></section>
<section className="topic-section"><div className="section-label">THE RESEARCH</div><div className="topic-columns"><div><h2>Machine learning-based automation of accounting services.</h2><p>Rodrigo Simon Bavaresco and co-authors, <em>International Journal of Accounting Information Systems</em>, Volume 49, Article 100618 (2023). DOI: 10.1016/j.accinf.2023.100618.</p></div><div><h3>Why it matters here</h3><p>This is a direct Topic 11 example: machine learning, automation and conversational interfaces applied to a real accounting management task.</p></div></div></section>
<section className="topic-section"><div className="section-label">CASE SNAPSHOT</div><div className="big-grid">{facts.map(([n,t,d])=><div key={n}><strong>{n}</strong><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="topic-callout"><span>THE RESULT</span><h2><em>10 / 10</em> users agreed the service was easy to use. <em>8 / 10</em> agreed the output was useful for reducing manual work.</h2></section>
<section className="topic-section"><div className="section-label">WHAT THE STUDY SHOWS</div><div className="big-grid"><div><strong>+</strong><h3>Less manual effort</h3><p>Participants reported a reduction in time associated with the accounting management task.</p></div><div><strong>+</strong><h3>Usable interface</h3><p>The chatbot approach was perceived as easy to use by the surveyed participants.</p></div><div><strong>!</strong><h3>Process fit matters</h3><p>Users raised questions about long-term usefulness when the automation had to accommodate particular process details.</p></div><div><strong>!</strong><h3>Adoption is human</h3><p>The research highlights user experience, awareness and training alongside the technology itself.</p></div></div></section>
<section className="workflow-card"><div><span>CASE → CLASSROOM DEMO</span><h2>Document → AI interface → automated processing → accountant review.</h2><p className="workflow-caption">The research gives the same logic as our Topic 11 demonstration: automate structured work, then keep human judgement close to the exception.</p></div><div className="mock-output"><small>ACADEMIC CASE</small><b>Bavaresco et al. (2023)</b><p>International Journal of Accounting Information Systems · 49 · 100618</p></div><div className="mock-output"><small>DOI</small><b>10.1016/j.accinf.2023.100618</b><p>Published research source.</p></div></section>
<section className="topic-section"><div className="section-label">SOURCE LINKS</div><div className="topic-columns"><div><h3>Google Scholar</h3><p>Search the exact paper title and review the academic record and citations.</p><a className="research-link" href="https://scholar.google.com/scholar?q=Machine+learning-based+automation+of+accounting+services%3A+An+exploratory+case+study" target="_blank" rel="noreferrer">OPEN SCHOLAR SEARCH ↗</a></div><div><h3>Direct DOI</h3><a className="research-link" href="https://doi.org/10.1016/j.accinf.2023.100618" target="_blank" rel="noreferrer">OPEN DOI ↗</a></div></div></section>
<footer className="topic-footer"><Link href="/future">06 / ← FUTURE</Link><Link href="/">00 / BACK TO INTRO →</Link></footer></main>}
